"""empty message

Revision ID: a1f36d4d43ec
Revises: 882798fc1644
Create Date: 2021-05-05 16:23:00.576222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f36d4d43ec'
down_revision = '882798fc1644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'entry',
        sa.Column('type', sa.SmallInteger(), server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'type')
    # ### end Alembic commands ###
